### ISSUE TITLE
`leipzig.melody/then` argument order

### ISSUE THREAD

**Issue by wontheone1** [ctford/leipzig#15]
as in below example

```clojure
(->>
  (phrase [3/3 3/3 2/3 1/3 3/3] ; Can you recognise the tune yet?
          [ 72  72  72  74  76])
  (then
    (phrase [2/3 1/3 2/3 1/3 3/3]
            [ 76  74  76  77  79])))
```
it becomes below with out the `->>` macro
```
(then 
  (phrase [2/3 1/3 2/3 1/3 3/3]
            [ 76  74  76  77  79])
  (phrase [3/3 3/3 2/3 1/3 3/3] ; Can you recognise the tune yet?
          [ 72  72  72  74  76]))
```

I find it pretty weird. why the phrase played later comes first?

if we reverse the order of argument then can take phrase in order without using `->>`
or if using threading macro is desired, then can use `->` macro.

I wonder why it is made like this currently and if you want to change it? I could try to pull off pull request if you want to change it.

Thanks.

**Comment by ctford** [comment]
Hi,

Sorry for missing your question many moons ago when you posted it.

The reason for the order is, as you deduced, to use the `->>` macro. You're right that if the order switched we could use the `->` macro instead, but that would break Clojure convention and would get weird when used with `where` etc.
