### ISSUE TITLE
Support CLJS

### ISSUE THREAD

**Issue by ctford** [ctford/leipzig#9]
Leipzig's dependence on Overtone is very slim - `at` and `now`. If we provide equivalents for CLJS, then Leipzig should be able to support music in the browser, using web audio instead of Overtone synths.

**Comment by yegortimoshenko** [comment]
Then you could drop Overtone as a dependency and instead use [`overtone/at-at`](https://github.com/overtone/at-at), which is the library that provides `at` and `now` for Overtone.

**Comment by yegortimoshenko** [comment]
This would fix #4 as well.

**Comment by bion** [comment]
overtone.core/at isn't provided by at-at:
https://github.com/overtone/overtone/blob/master/src/overtone/sc/server.clj#L52

Overtone provides all of the scsynth interop. Rewriting all of the UGens
and synthesis graph traversal logic for web audio would likely be the
biggest chunk of work. If you're interested in making that happen in the
browser you may take a look at CoffeeCollider, which has most of that
functionality: https://github.com/mohayonao/CoffeeCollider

**Comment by ctford** [comment]
As Leipzig is designed now, it doesn't actually have a direct dependency on
ugens. The way you invoke an instrument is to implement a multimethod, so
if you e.g. wanted to use CoffeCollider, you could (so long as we take care
of `at` and `now` somehow.

**Comment by ctford** [comment]
Leipzig now supports CLJS and is now used in Klangmeister (https://ctford.github.io/klangmeister).
